package com.bluechat.presentation.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0062A1)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD0E4FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001D35)
val md_theme_light_secondary = Color(0xFF525F70)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD6E4F7)
val md_theme_light_onSecondaryContainer = Color(0xFF0F1D2A)
val md_theme_light_tertiary = Color(0xFF6A5779)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF1DBFF)
val md_theme_light_onTertiaryContainer = Color(0xFF241532)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDFCFF)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFDFCFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFDFE2EB)
val md_theme_light_onSurfaceVariant = Color(0xFF43474E)

val md_theme_dark_primary = Color(0xFF9BCAFF)
val md_theme_dark_onPrimary = Color(0xFF003257)
val md_theme_dark_primaryContainer = Color(0xFF00497B)
val md_theme_dark_onPrimaryContainer = Color(0xFFD0E4FF)
val md_theme_dark_secondary = Color(0xFFBAC8DB)
val md_theme_dark_onSecondary = Color(0xFF243240)
val md_theme_dark_secondaryContainer = Color(0xFF3A4857)
val md_theme_dark_onSecondaryContainer = Color(0xFFD6E4F7)
val md_theme_dark_tertiary = Color(0xFFD5BEE5)
val md_theme_dark_onTertiary = Color(0xFF3A2A48)
val md_theme_dark_tertiaryContainer = Color(0xFF514060)
val md_theme_dark_onTertiaryContainer = Color(0xFFF1DBFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C1E)
val md_theme_dark_onBackground = Color(0xFFE3E2E6)
val md_theme_dark_surface = Color(0xFF1A1C1E)
val md_theme_dark_onSurface = Color(0xFFE3E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF43474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC3C7CF)

// Custom colors
val Blue40 = Color(0xFF4F86C6)
val Blue80 = Color(0xFF7EB3FF)
val DarkBlue = Color(0xFF1E3A8A)
val LightBlue = Color(0xFFE6F0FF)
val ErrorRed = Color(0xFFFF6B6B)
val SuccessGreen = Color(0xFF4CAF50)
val WarningYellow = Color(0xFFFFC107)

// Chat colors
val SentMessage = Color(0xFFE3F2FD)
val ReceivedMessage = Color(0xFFF5F5F5)
val OnlineStatus = Color(0xFF4CAF50)
val OfflineStatus = Color(0xFF9E9E9E)
val TypingIndicator = Color(0xFF2196F3)
