name: Android CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Install Gradle
      run: |
        # Install Gradle
        sudo apt-get update
        sudo apt-get install -y gradle
        gradle -v
        
    - name: Build and Test
      run: |
        # Build the project
        gradle build
        # Run tests
        gradle test
        
    - name: Build release APK
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
      env:
        KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: |
        # Only attempt to build release if keystore is available
        if [ -n "$KEYSTORE_FILE" ]; then
          echo "$KEYSTORE_FILE" | base64 -d > keystore.jks
          gradle assembleRelease \
            -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/keystore.jks \
            -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$KEY_PASSWORD
          rm -f keystore.jks
        else
          echo "Skipping release build - missing keystore configuration"
        fi
      
    - name: Upload APK artifacts
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
      uses: actions/upload-artifact@v4
      with:
        name: app-builds
        path: |
          app/build/outputs/apk/debug/*.apk
          app/build/outputs/apk/release/*.apk
        if-no-files-found: warn